#!/usr/bin/bash
calculate_product_of_factors() {
	if [ $# -ne 3 ]; then
		args=("$@")
			product=1
			for a in "${args[@]:2}"; do
				product=$(echo "$a * $product" | bc)
					done
	else
		product=$3
			fi

			num1=$2
			num=$(echo "$1" | tr ':' '=')

			if [ $(echo "$product > $num1" | bc) -eq 1 ]; then
				temp=$num1
					num1=$product
					product=$temp
					fi

					echo "$num$num1*$product"
}

if [ $# -ne 1 ]; then
echo 'Usage: factors <file>'
exit 1
else
while read number; do
factors_result=$(factor "$number")
calculate_product_of_factors $factors_result
done < "$1"
fi

